### ISSUE TITLE
The GUI shows nothing

### ISSUE THREAD

**Issue by emerld2011** [pkindt/WirelessEye#2]
Thank you very much for the great contribution！ I have tried my device Raspberry 4B with nexmon. However, I followed the installation steps and GUI showed nothing.
![image](https://user-images.githubusercontent.com/45532333/166159425-de985463-7adb-4538-96a8-4a6e43518922.png)
![image](https://user-images.githubusercontent.com/45532333/166159440-36dd337c-9ff4-46b1-8dc8-30536e3dd7be.png)
I used TCP, should I ping the Raspberry Pi first?

**Comment by pkindt** [comment]
Hello,

did you ensure that Nexmon is actually capturing something, e.g., using tcpdump on the Pi (See the how-tos in the Nexmon GIT) ? It appears that from the side of WiFiEye, everything works as it should.

Best Regards,

Philipp

**Comment by emerld2011** [comment]
Thank you so much, pkindt! I have used tcpdump as you said and the problem is solved!

**Comment by pkindt** [comment]
Thanks for letting us know.
